### PR TITLE
Tag filtering on blog pages

### PR DESCRIPTION
**Pull request by thomasjthomasj**
This PR integrates the filtering component by creating a 'Filter by Tag' for to go on the blog listing.

Requires:
CMS: https://github.com/mothership-ec/cog-mothership-cms/pull/267
Cog: https://github.com/mothership-ec/cog/pull/440

### CODE REVIEW

**Comment by kuiche** [comment]
Use SQL pagination in the blog!

**Comment by kuiche** [comment]
This loads all tags. "header" and "submenu" are loaded when they shouldn't be. Perhaps the TagLoader needs to have a getChildTags(Page $page)/getSiblingTags(Page $page)?

**Comment by thomasjthomasj** [comment]
@kuiche Hmm, I think the issue is more than the tag-based menus shouldn't be part of the base installation. This implementation is really supposed to be an example usage so I'm not sure having to rejig the tag loader is the best approach. If we wanted to do a quicker fix in the interim we could just add a tag blacklist to the service when we set the options

**Comment by kuiche** [comment]
@thomasjthomasj that could be a solution. Or we could just give it an array of possible tags. Then we can define the possible categories of the blog posts which may be desirable. Getting all tags with a blacklist doesn't account for tags added later. Getting siblings doesn't account for possible tags added later to blog posts.

What would really be good is a page in the admin panel where the possible tags (or blog categories) could be set though that is way out of scope for this update.

**Comment by thomasjthomasj** [comment]
@kuiche No I think an array of possible tags is rigid and less futureproof than a blacklist, but since this has been sitting around for a while I might just sort the menu out

**Comment by thomasjthomasj** [comment]
This PR now requires https://github.com/mothership-ec/cog-mothership-cms/pull/267 to resolve this issue

**Pull request closed without merging**
